// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Wkg1Xy935JhBK66oyYRVcy-xNm7jwdo',
    appId: '1:853041049978:web:c675a3189f45d23924e6c3',
    messagingSenderId: '853041049978',
    projectId: 'boschetto-unibo-cesena',
    authDomain: 'boschetto-unibo-cesena.firebaseapp.com',
    storageBucket: 'boschetto-unibo-cesena.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAExV_MkSOQgPXAzNOIEAcyfELWRtXj_uw',
    appId: '1:853041049978:android:24a67f834f652e1624e6c3',
    messagingSenderId: '853041049978',
    projectId: 'boschetto-unibo-cesena',
    storageBucket: 'boschetto-unibo-cesena.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBMaNFVO4_a_GRQgarB5zz70O1-8Od_YQ',
    appId: '1:853041049978:ios:32b4e83db66093aa24e6c3',
    messagingSenderId: '853041049978',
    projectId: 'boschetto-unibo-cesena',
    storageBucket: 'boschetto-unibo-cesena.appspot.com',
    iosClientId:
        '853041049978-lvdbqji81l18c5382vtn902cobffjtuq.apps.googleusercontent.com',
    iosBundleId: 'it.unibo.treeAr',
  );
}
